# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
baseurl:        "/"
url:            "https://smartshouse.github.io"

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
